name: Linux

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:

jobs:
  raku:
    strategy:
      matrix:
        os:
          - ubuntu-latest
        raku-version:
          - '2024.10'
          - 'latest'
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: Raku/setup-raku@v1
        with:
          raku-version: ${{ matrix.raku-version }}
      - name: install packages
        run: sudo apt-get install -y curl libcurl4-gnutls-dev 
      - name: Install native deps
        run: ./install_deps.sh
      - name: Install Dependencies
        run: zef install --deps-only .
      - name: Run Tests
        run: LD_LIBRARY_PATH=/usr/local/lib zef test -v .
